version: '3'
services:
  s3:
    build: .
    entrypoint: python exporter.py
    working_dir: /opt/prometheus-s3-exporter
    volumes:
      - ./app:/opt/prometheus-s3-exporter:rw
      - ./config:/config:ro
    ports:
      - 9327:9327
